### ISSUE TITLE
might be a stupid question, but how do I use this?

### ISSUE THREAD

**Issue by Erinm0re** [MonstrousOgre/lkb-map#1]
I just switched from Windows, and have no experience yet in linux whatsoever (I plan to change that, but it takes time).. I searched the internet for a way, to customize my Tartarus V2, and I found your Reddit Post. could you, if its not too much trouble, explaining this to a noob, explain me, how I use it?

**Comment by MonstrousOgre** [comment]
@DrPearl this isn't in a working stage yet. I'd started working on it but [someone did beat me to it](https://github.com/sezanzeb/key-mapper). I'll continue working on mine since it's written in Rust and has no dependencies, but there's currently a better option.

**Comment by Erinm0re** [comment]
Thanks for the awnser :) I'll try that one out. have a nice Sunday
